---

- name: "Imperative: Run a tmsh command"
  hosts: all
  gather_facts: False
  connection: local

  environment: "{{ bigip_env }}"

  tasks:
    - name: View system version and LTM configuration
      bigip_command:
	  server: "{{ inventory_hostname }}"
	  user: "{{ username }}"
	  password: "{{ password }}"
        commands:
          - show /sys version detail
          - list /ltm virtual all
          - list /ltm pool all
          - list /ltm node all
      register: result

    - debug: msg="{{ result.stdout_lines }}"

...
