---

- name: Get iApp service list
  uri:
    url: "https://{{ inventory_hostname }}/mgmt/tm/cloud/services/iapp/"
    user: "{{ username }}"
    password: "{{ password }}"
    validate_certs: no
    return_content: yes
  register: service_list
...
